# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CookDocs < Formula
  desc "A tool for automatically generating markdown documentation for cooklang recipes"
  homepage "https://nicholaswilde.io/cook-docs"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.5.0/cook-docs_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "d58faef7e024e0e5605f5420ab0145ee2bf7ddce2ebccbf21300d3c67d015aa3"

      def install
        bin.install "cook-docs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.5.0/cook-docs_0.5.0_Darwin_arm64.tar.gz"
      sha256 "990fa25b21e43057ec84823bfe3c54865bf452feed10f2c99f45e1d9c6b3cc73"

      def install
        bin.install "cook-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.5.0/cook-docs_0.5.0_Linux_armv6.tar.gz"
      sha256 "49c8ac4a18201fc5374f53654de9773a284397d26e88c35716d4900181a9bb4a"

      def install
        bin.install "cook-docs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.5.0/cook-docs_0.5.0_Linux_x86_64.tar.gz"
      sha256 "18d52c32a73d0f4ac4c819e120113589852b218719ee1d79ab51e7375035c0be"

      def install
        bin.install "cook-docs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.5.0/cook-docs_0.5.0_Linux_arm64.tar.gz"
      sha256 "e60c7be0752537d491898dc847c00bd2f1b1ec41e5b81440a7acc2dfb7d83761"

      def install
        bin.install "cook-docs"
      end
    end
  end

  test do
    system "#{bin}/cook-docs --version"
  end
end
