# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CookDocs < Formula
  desc "A tool for automatically generating markdown documentation for cooklang recipes"
  homepage "https://nicholaswilde.io/cook-docs"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.6.1/cook-docs_0.6.1_Darwin_x86_64.tar.gz"
      sha256 "724f4ad729a75d188bd715279b791001e016132461242d3927965fd9f4fd8537"

      def install
        bin.install "cook-docs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.6.1/cook-docs_0.6.1_Darwin_arm64.tar.gz"
      sha256 "57d68b7aa053aa8415708be4d3b537acce298adfed50510d56ef1aac389db8eb"

      def install
        bin.install "cook-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.6.1/cook-docs_0.6.1_Linux_armv6.tar.gz"
      sha256 "33c4b533eb11d564db5cc0654efd76dfff8bbd026f4c918ccab36eec80e8a8ad"

      def install
        bin.install "cook-docs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.6.1/cook-docs_0.6.1_Linux_arm64.tar.gz"
      sha256 "1f2a08136e402f6b7dec6b3a64854e2f7c1d1f47c4f9b71ff2bec5820f28e248"

      def install
        bin.install "cook-docs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nicholaswilde/cook-docs/releases/download/v0.6.1/cook-docs_0.6.1_Linux_x86_64.tar.gz"
      sha256 "ab567a099d904af0f4c1a6e697c118f0aa045ef06d6f29b6acbac3e69909268e"

      def install
        bin.install "cook-docs"
      end
    end
  end

  test do
    system "#{bin}/cook-docs --version"
  end
end
